### ISSUE TITLE
laravel5.4支持吗？

### ISSUE THREAD

**Issue by dishcheng** [MissMyCat/aliyun-sms#1]
我是laravel5.4...每次刷新都报错如下：
{#1677 ▼
  +"Message": "未开通云通信产品的阿里云客户"
  +"RequestId": "9A1FF519-FD2E-45BE-9236-35FB55B0E3DC"
  +"Code": "isv.PRODUCT_UN_SUBSCRIPT"
}
配置都是对的，，，工单也问了，服务确实开了，请问是不支持laravel5.4吗？

**Comment by MissMyCat** [comment]
我确认是支持的，因为我自己用的就是这个laravel版本。根据你的报错信息，你可以检查下你阿里云账号权限是否开通了。然后access key 和 secret key 有没有写对。

**Comment by dishcheng** [comment]
access key 和 secret key 没有写对的话就直接报错了，阿里云账号权限在哪里看啊？可以加微信或者qq了解一下吗？

**Comment by MissMyCat** [comment]
314463646 企鹅

**Comment by MissMyCat** [comment]
阿里云账号配置问题，和laravel版本无关。
