### ISSUE TITLE
调用多次`$sms->sendSms`会抛出异常

### ISSUE THREAD

**Issue by kokororin** [MissMyCat/aliyun-sms#2]
`Constant ROOT_PATH already defined`，
错误行https://github.com/MissMyCat/aliyun-sms-sdk/blob/master/aliyun-php-sdk-core/Profile/DefaultProfile.php#L47
同时`ROOT_PATH`可能会和一些框架冲突，建议修改一下

**Comment by MissMyCat** [comment]
OK  明白你意思了~非常感谢，我会把这块加上判断。

**Comment by MissMyCat** [comment]
好的，我更新了这个sdk，你可以重新尝试下：
` composer update mrgoon/* `

**Comment by kokororin** [comment]
感谢，已经可以啦
