### ISSUE TITLE
未开通云通信产品的阿里云客户

### ISSUE THREAD

**Issue by hkzj0571** [MissMyCat/aliyun-sms#3]
{#1461 ▼
  +"Message": "未开通云通信产品的阿里云客户"
  +"RequestId": "982DDFD1-621D-495A-81B9-77DE64C42E42"
  +"Code": "isv.PRODUCT_UN_SUBSCRIPT"
}

明明在阿里控制台已经开通了啊

**Comment by MissMyCat** [comment]
这个使用的是阿里云的**短信服务**。进到控制台能看到：
![default](https://user-images.githubusercontent.com/16793979/29555975-ef995a14-8756-11e7-806b-0c5b0264e4a1.png)
怎么说呢，阿里云说你没搞对，那就应该是没搞对了，再研究下呗。

**Comment by hkzj0571** [comment]
access_key access_secret  不在在Access Key管理里面的吗

**Comment by MissMyCat** [comment]
你需要在.env里面配置你的AC_KEY 和 AS_KEY；数据来是Access Key管理

**Comment by hkzj0571** [comment]
这些我都配置过了，但还是不行，我QQ 897760408
