### ISSUE TITLE
引用的GuzzleHttp包是哪个版本的？

### ISSUE THREAD

**Issue by bajian** [MissMyCat/aliyun-sms#4]
我的laravel5.4好像没有这个包，引入"guzzlehttp/guzzle": "~6.0"提示构造函数参数类型不对

Type error: Argument 2 passed to GuzzleHttp\Exception\BadResponseException::__construct() must be an instance of Psr\Http\Message\RequestInterface, string given, called in X:\Users\bajian\Desktop\code\server\washingcar\vendor\mrgoon\aliyun-sms-sdk\aliyun-php-sdk-core\DefaultAcsClient.php on line 122
--
 
引用
```
throw new ServerException($respObject->Message, $respObject->Code, $httpStatus, $respObject->RequestId);
```
类中构造函数
```
public function __construct(
        $message,
        RequestInterface $request,
        ResponseInterface $response = null,
        \Exception $previous = null,
        array $handlerContext = []
    )
```

**Comment by MissMyCat** [comment]
`
"extra": {
        "branch-alias": {
            "dev-master": "6.2-dev"
        }
    }
`

可以尝试一下6.2-dev

**Comment by bajian** [comment]
没有错哇，官方的构造函数的参数类型不一样的。
https://github.com/guzzle/guzzle/blob/master/src/Exception/BadResponseException.php

**Comment by MissMyCat** [comment]
我查看了一下mrgoon\aliyun-sms-sdk\aliyun-php-sdk-core\DefaultAcsClient.php on line 122 这个地儿的代码。
出这个问题是由于http response 返回状态为false，应该和GuzzleHttp包关系不是特别的大。
你可以贴出来你使用这个SMS sdk 的代码嘛？

**Comment by bajian** [comment]
只要是配置或者参数不对等非OK返回，就会跑那行去了，httpstatus 为400.配置正常就不会走那个逻辑。
```
object(stdClass)#1485 (4) { ["Message"]=> string(38) "SignName is mandatory for this action." ["RequestId"]=> string(36) "4F270BBA-7631-4046-AD13-D459812A4D9F" ["HostId"]=> string(21) "dysmsapi.aliyuncs.com" ["Code"]=> string(15) "MissingSignName" } int(400)
```
配置正常后就不会走那逻辑了。不改也行。不过我不清楚到时候余额不足会不会也跑那行去了，到时候就会报错了

**Comment by MissMyCat** [comment]
可能是你在外部对这个response做了拦截吧……我在直接用的时候，都是可以打印出来所有的正确错误信息。

**Comment by MissMyCat** [comment]
@bajian 今天更新的时候找出来了个这个BUG,是在mrgoon\aliyun-sms-sdk\aliyun-php-sdk-core\DefaultAcsClient.php 这个文件中use的Exception不对。之前用的是GuzzleHttp下的Exception，现已改成Aliyun-sdk内的Exception。

**Comment by bajian** [comment]
好的
