### ISSUE TITLE
dev-master出现的.git目录问题

### ISSUE THREAD

**Issue by Birjemin** [MissMyCat/aliyun-sms#5]
遇到了composer install的时候把.git目录都拉下来了
希望楼主处理一下
http://blog.csdn.net/allen_tsang/article/details/75212310
感谢！

**Comment by MissMyCat** [comment]
非常抱歉。这个项目在github上发布了三个不同的版本， packagist.org上只同步到了2个版本dev-master和1.0.0。并没有很好地解决包依赖的问题。如果这个漏洞对您的工作造成了影响，实在抱歉，可能需要您手动删除.git这个目录了。
